# Generated by Django 4.1.7 on 2023-03-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
